### ISSUE TITLE
Not able to drag row in list view, but handle is showing

### ISSUE THREAD

**Issue by johansoetewey** [jrief/django-admin-sortable2#201]
I'm having a problem with latest version of django-admin-sortable2.
Problem is that it not possible to drag a row. But it does show the drag hand and image.

Our biggest changes are moving to Python 3, Django 2.1, latest version of django-admin-sortable2 (07/08). 

Before the migration it was Python 2.7 and Django 1.8.

My admin code looks as following (short version):
```
from django.contrib import admin
from adminsortable2.admin import SortableAdminMixin, SortableInlineAdminMixin

from .models import *

class FilmAdmin(SortableAdminMixin, admin.ModelAdmin):
    list_display = (
        'priority',
        'project_id',
        'title',
        'director',
        'year',
        'url_friendly_name',
        'show_on_website',
        'frontpage'
    )
    list_display_links = (
        'project_id'
    )
    list_editable = (
        'url_friendly_name',
        'show_on_website',
        'frontpage'
    )
    readonly_fields = ('project_id',)
    inlines = [
        InlineFilmSlide,
        InlineSubtitle,
        InlineScreening,
        InlineAward,
        InlineFilmCoproduction,
        InlineFilmProduction,
        InlineFilmSupportOrganisation
    ]

    def project_id(self, obj):
        return obj.project_id()

admin.site.register(Film, FilmAdmin)
```

My model looks as following (short version):
```
class Film(models.Model):
    priority = models.PositiveIntegerField(default=0, blank=False, null=False)

    class Meta(object):
        ordering = ['priority']
```

Priority is the sortable field.

**Comment by russian-master** [comment]
Same for me. Tried different tricks in admin, no luck. I can see handles in the list but can't drag them.
adminsortable2 js and css files are succesfully loaded.

Django==1.11.16 Python 2.7
django-admin-sortable2==0.6.21

**Comment by ShadowLNC** [comment]
Confirmed with Django 2.2 Python 3.7 - looking in Dev Tools, I see several `$` is not defined/not a function errors, and that `django.jQuery` is not a function (as the first error). Appears that jQuery is not loading correctly, and this issue may be related to #185. Currently, this package is unusable as a result.

**Comment by jrief** [comment]
In Django's Changelog, is there anything related to this problem?

**Comment by kaduuuken** [comment]
the problem is, that Django requires the jquery to be implemented now: https://docs.djangoproject.com/en/2.2/releases/2.2/#merging-of-form-media-assets

i fixed that issue by adding `'admin/js/jquery.init.js'` to `SortableInlineAdminMixin` in `admin.py` line 459

**Comment by wwarne** [comment]
Just install django 2.1.8 to verify - everything worked fine. After updating to 2.2 sortable models are not sortable anymore. For some reason Django puts script `adminsortable2/js/list-sortable.js` before `admin/js/jquery.init.js` in resulting HTML page. It causes errors like `django.jQuery is not a function`.

Unfortunately the @kaduuuken solution didn't help.

Temporally I ended up with moving JS resources inside my app's `admin.py` like this:
```
class FilterTitleAdmin(SortableAdminMixin, admin.ModelAdmin):    
    class Media:
        js = (
            'admin/js/vendor/jquery/jquery.js',
            'admin/js/jquery.init.js',
            'adminsortable2/js/plugins/admincompat.js',
            'adminsortable2/js/libs/jquery.ui.core-1.11.4.js',
            'adminsortable2/js/libs/jquery.ui.widget-1.11.4.js',
            'adminsortable2/js/libs/jquery.ui.mouse-1.11.4.js',
            'adminsortable2/js/libs/jquery.ui.sortable-1.11.4.js',
            'adminsortable2/js/list-sortable.js',
            'adminsortable2/js/inline-sortable.js',
        )
```
With this piece of code Django is sorting assets in a right order and everything is working.

**Comment by bengosney** [comment]
This looks to have been fixed, just not released to pypi yet
https://github.com/jrief/django-admin-sortable2/commit/c2ff4d0274e98db6e12b4fe57ab2e77a88ed53f2

**Comment by jrief** [comment]
Version 0.7.1 containing this fix has been published now.
